version: '3'
services: 
  server1:
    image: nginx
    ports:
      - "8080:80"
    volumes: 
      - d:/code/belajar-docker/html:/usr/share/nginx/html
  server2:
    image: nginx
    ports:
      - "8081:80"
    volumes: 
      - d:/code/belajar-docker/html:/usr/share/nginx/html
  mysql: 
    image: mysql
    environment: 
      MYSQL_DATABASE: "todo"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes: 
      - d:/code/belajar-docker/mysql_data:/var/lib/mysql
    networks:
      - network1
  phpmyadmin:
    image: phpmyadmin
    ports: 
      - "8082:80"
    environment:
      PMA_HOST: mysql
    networks:
      - network1
networks: 
  network1:
    driver: bridge
